apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-secrets-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list","create","update","patch","delete"]