apiVersion: v1
kind: Secret
metadata:
  name: worker-config
type: Opaque
data:
  OPERETO_HOST: "{{ .Values.workerSettings.OPERETO_HOST | b64enc }}"
  OPERETO_TOKEN: "{{ .Values.workerSettings.OPERETO_TOKEN | b64enc }}"
