apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster.name: opereto-database-cluster
    network.host: "0.0.0.0"
    discovery.zen.ping.unicast.hosts: opereto-es
    discovery.zen.minimum_master_nodes: 1
    cluster.initial_master_nodes:
    - opereto-es-node-0
    - opereto-es-node-1
    - opereto-es-node-2
  ES_JAVA_OPTS: {{ .Values.javaOpts }}