apiVersion: v1
kind: Service
metadata:
  name: opereto-database
spec:
  type: ClusterIP
  ports:
  - port: 9200
    name: serving
  - port: 9300
    name: internal
  selector:
    app: opereto-es-cluster